spring.application.name=backend
server.port=${PORT:8080}
server.address=0.0.0.0
#postgreSql
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.exp-minutes=60

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test.colak@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# opsiyonel
spring.mail.default-encoding=UTF-8


